### ISSUE TITLE
Can you elaborate why Polly is a pain to debug?

### ISSUE THREAD

**Issue by jzabroski** [SanderSade/Sander.MultiTry#1]
Thanks for this library.

**Comment by SanderSade** [comment]
Coworker was using Polly to handle a complex, multi-part operation - and on occasion Polly simply did not re-try. I cannot remember for sure, but think in the end he traced it to a faulty Polly setup, but it took him a long, long while to find the issue. That said, I still think that Polly is a most excellent library, and heartily recommend it.

And you're most welcome!

**Comment by jzabroski** [comment]
Can we ask him to share his experience here? :)

Just curious for two reasons:

1. To improve as an engineer.  Planning to recommend Polly at work.
2. I'm also currently helping Microsoft improve the documentation around HttpClient. See: https://github.com/dotnet/dotnet-api-docs/pull/2315 - Currently, Microsoft **unofficially** (but officially in the sense their [best practices documentation says use Polly](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)) recommends Polly for transient fault handling.

**Comment by SanderSade** [comment]
I actually think Polly is more popular outside MS then in-house - largely still due to that damn old NIH (Not Invented Here) syndrome that we as a company have...

Just talked with the coworker - he cannot remember for sure, but thinks it was when he upgraded Polly to a newer version then retries stopped working without any error messages (both compilation & runtime). Once he got it back to work it was flawless, so he has used it again in other projects.

**Comment by SanderSade** [comment]
Going to close this, no new questions/comments
